### ISSUE TITLE
Too many console.log statements

### ISSUE THREAD

**Issue by jrattanpal** [mshanemc/deploy-to-sfdx#63]
With the latest change, there is a console.log statement every 1-2 seconds. There are just too many logs in the end in browser console.

Can this be changed back to original where it only logged when status changed?
![sfdx_console_log_errors](https://user-images.githubusercontent.com/7070636/64278044-d408f680-cf19-11e9-8ac3-e34337cfc170.png)

**Comment by mshanemc** [comment]
Had to switch to polling because of browser support and firewall issues around web sockets.

What’s the issue caused by the logging?

**Comment by jrattanpal** [comment]
It's not a blocker.

It just adds too many statements. My computer (macbook air) is slow and all these messages make it even slower. 

in our case, it took about 15-20 minutes for app to install. And there were all these messages every 1-2 seconds during that and that was too many.

**Comment by mshanemc** [comment]
this is fixed...only logs when something about the CDS changes.
