### ISSUE TITLE
deploy-to-sfdx seems to be able to deploy only public repos

### ISSUE THREAD

**Issue by RupertBarrow** [mshanemc/deploy-to-sfdx#65]
Line 26 in lib/deployMsgBuilder
`const path = template.replace('https://github.com/', '');`
seems to prove that deploy-to-sfdx does not launch private GitHub templates whose path is `https://user:pwd@github.com/`

Would it be possible to manage authentication with GitHub :
- either with the `https://user:pwd@github.com/` syntax,
- or with a GitHub PAT (personal access token) ?

**Comment by mshanemc** [comment]
you're not the first person to ask.  

How are you planning to keep anyone from hitting your instance of the deployer, getting an org, and looking at whatever you were trying to keep private?

**Comment by RupertBarrow** [comment]
Thanks for your answer, Shane.

For the moment, I am exploring solutions, testing my own hosted version of deploy-to-sfdx.

Requests to deploy will always be internally by people from our company - ditto for our repos, which will be private to the company.
So, to answer your question : we will protect access to the Heroku app, as well as put restrictions on the origin of calls to it.


If we had all our repos in the same GitHub account, we could use a GitHub PAToken.
Better would be to manage the https://user:pwd@github/user/repo syntax.


What do you think ?

**Comment by mshanemc** [comment]
I would never want my github credentials bouncing around server logs, browser urls, firewalls, google analytics, or other people's apps.  And there's also the scenario where you've got 2FA on github (not sure what url-based auth does in that case to complete).

Would definitely recommend using something like this buildpack and storing a token scoped to read-only.
https://github.com/timshadel/heroku-buildpack-github-netrc

Then, your deployer would have access to git-clone whatever repos it can based on that token, and it's easy to revoke or whatever from github should it need to be.

As a bonus, you don't have to touch the code on the deployer--just cause a rebuild to happen.

**Comment by mshanemc** [comment]
Done, via buildpack, so it works on this project OR OTHERS
https://github.com/mshanemc/github-via-pat

README says more.
