### ISSUE TITLE
Branches are case sensitive in git, but deployer forces lowercase

### ISSUE THREAD

**Issue by jhaydraude** [mshanemc/deploy-to-sfdx#73]
When trying to deploy from a branch where the branch name is MixedCase, deployer fails. This issue is new since Jan 22, 2020 
Example repo:
https://github.com/rreboucas/sparkle-dx/tree/SparkleADK

Using the latest commit prior to Jan 22 the clone command is:
git clone -b SparkleADK --single-branch https://github.com/rreboucas/sparkle-dx.git rreboucas-sparkle-dx-158395585139371

Using the latest master commit the clone command is:
git clone -b sparkleadk --single-branch https://github.com/rreboucas/sparkle-dx.git rreboucas-sparkle-dx-1583956074826ad

And the error:
warning: Could not find remote branch sparkleadk to clone. fatal: Remote branch sparkleadk not found in upstream origin

**Comment by mshanemc** [comment]
fixed
