### ISSUE TITLE
Question about an error, deploying example repo mshanemc/df17AppBuilding

### ISSUE THREAD

**Issue by RupertBarrow** [mshanemc/deploy-to-sfdx#75]
Hi Shane,
I've just set up deploy-to-sfdx, and tried deploying mshanemc/df17AppBuilding as an example. I'm getting the following error : 

2020-04-04T21:15:32.459990+00:00 app[orgbuilder.1]: status=1 name=TypeError message="error running line sfdx shane:org:create -f config/project-scratch-def.json -s -d 1 --userprefix crash --userdomain course.org --json from deploy that includes rupertbarrow/df17appbuilding: Cannot read property 'orgId' of undefined" exitCode=1 commandName=CreateOrg stack="TypeError: Cannot read property 'orgId' of undefined

I have cloned deploy-to-sfdx, activated all the dynos, checked that auth is going well : 
### auth res =  {
    stdout: '{\n' +
     '  "status": 0,\n' +
     '  "result": {\n' +
     '    "orgId": "00D1i000000U______",\n' +
     '    "accessToken": "YYY",\n' +
     '    "instanceUrl": "https://XXX.my.salesforce.com",\n' +
     '    "loginUrl": "https://login.salesforce.com",\n' +
     '    "username": "user@domain.org",\n' +
     '    "clientId": "123",\n' +
     '    "privateKey": "/app/tmp/server.key"\n' +
     '  }\n' +
     '}\n',
    stderr: ''
}

Have you got an idea of what could be the problem ?

**Comment by mshanemc** [comment]
I’d try is with the regular org:create first, then with my custom one.

It **could** be the plugin and not the deployer that has a problem.  I think I saw that once before—there’s an error in the scratch def usually causing that

**Comment by RupertBarrow** [comment]
Interesting stuff.
My self-signed certificate was expired.
SFDX Auth was working OK, but SFDX org create was failing.

`sfdx force:org:create`
gave me an explicit error message : something like certificate expired.
However, 
`sfdx shane:org:create `
did not give me a clear error message.

**Comment by mshanemc** [comment]
I know...that plugin was overly optimistic.  It also bites me when scratch defs become invalid across releases.  It needs to just throw when anything goes wrong
