### ISSUE TITLE
Dyno in an exit loop when the pool is empty

### ISSUE THREAD

**Issue by tbalthazar** [mshanemc/deploy-to-sfdx#90]
Hi @mshanemc,

Looking at [the Procfile](https://github.com/mshanemc/deploy-to-sfdx/blob/f33d7016a0856fe964b4f7222fdd72edd3af29e1/Procfile#L4), I noticed that [the process that monitors the pool](https://github.com/mshanemc/deploy-to-sfdx/blob/f33d7016a0856fe964b4f7222fdd72edd3af29e1/src/server/processes/poolConsumer.ts#L11) exits every time the [pool is empty](https://github.com/mshanemc/deploy-to-sfdx/blob/f33d7016a0856fe964b4f7222fdd72edd3af29e1/src/server/lib/poolBuild.ts#L17), causing the dyno to restart each time.

If the pool is empty most of the time, it means the dyno will be on an exit loop, constantly restarting.
I don't know the specifics of this application and I'm not a Javascript expert, so please forgive me if I'm missing something, but I'm wondering if something like this would work better for this use case:

```javascript
import { poolBuild } from '../lib/poolBuild';

(async () => {
    while (true) {
        let builtSomething = await poolBuild();
        if (!builtSomething) {
            // the pool is empty, let's wait N seconds and try again
            sleep(5);
        }
    }
})();
```

What do you think?

**Comment by mshanemc** [comment]
That process should have 0 "normal" dynos running.  It runs via one-off dynos [initiated](https://github.com/mshanemc/deploy-to-sfdx/blob/f33d7016a0856fe964b4f7222fdd72edd3af29e1/src/server/processes/poolMaintenance.ts#L11) by the `poolwatcher` process  

this project uses [one-off dynos](https://devcenter.heroku.com/articles/one-off-dynos) and queues for elastic scale and efficiency

docs about heroku setup: https://github.com/mshanemc/deploy-to-sfdx#heroku-setup

**Comment by tbalthazar** [comment]
Thanks for the clarification and quick answer @mshanemc!
